copy_on_select yes

cursor_shape          beam
cursor_blink_interval 0

font_family MonoLisa
bold_font MonoLisa Bold
italic_font MonoLisa Italic
bold_italic_font MonoLisa Bold Italic

font_size 13.0
adjust_line_height 110%

enable_audio_bell no
macos_option_as_alt yes
hide_window_decorations yes
macos_show_window_title_in none

window_padding_width 20
remember_window_size no
initial_window_width 160c
initial_window_height 48c

shell_integration enabled
strip_trailing_spaces never

scrollback_lines 10000

allow_hyperlinks yes
detect_urls yes

confirm_os_window_close 0

startup_session none

kitty_mod cmd

map ctrl+z close_window
map cmd+shift+r load_config_file

map alt+backspace send_text all \x1b\x7f
map cmd+backspace send_text all \x15

enabled_layouts splits
map cmd+r launch --location=vsplit --cwd=current
map cmd+enter launch --location=vsplit --cwd=current
map cmd+u launch --location=hsplit --cwd=current

map cmd+h neighboring_window left
map cmd+j neighboring_window down
map cmd+k neighboring_window up
map cmd+l neighboring_window right

map cmd+n next_window
map cmd+p previous_window

map page_up scroll_page_up
map page_down scroll_page_down

shell .

include ~/.config/kitty/current_theme.conf

