tap "gromgit/fuse"
tap "mongodb/brew"
tap "shivammathur/php"
tap "symfony-cli/tap"
brew "antidote"
brew "aom"
brew "cairo"
brew "ffmpeg"
brew "freetds"
brew "jpeg-xl"
brew "libavif"
brew "gd"
brew "git"
brew "htop"
brew "python@3.14"
brew "httpie"
brew "libmagic"
brew "libpq", link: true
brew "lsd"
brew "mcfly"
brew "mysql-client"
brew "neovim"
brew "openjdk@17"
brew "openssl@1.1"
brew "php@8.2", link: true
brew "python@3.11"
brew "ripgrep"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "shivammathur/php/php@7.4", link: true
brew "symfony-cli/tap/symfony-cli"
cask "font-fira-code"
cask "kitty"
cask "redis-insight"
